Repository WildCodeSchool-2023-09/php-p2-straszik, pull requests merged in 2023-10, with the labels that each got.

#3 Ajout du footer + fichier css global pour le footer en bas de page et…
  public/assets/css/_footer.css
  public/assets/css/_global.css
  public/assets/css/_variables.css
  public/assets/css/style.css
  public/assets/images/icons/Icone_Deezer.svg
  public/assets/images/icons/Icone_Facebook.svg
  public/assets/images/icons/Icone_Instagram.svg
  public/assets/images/icons/Icone_Spotify.svg
  public/assets/images/icons/Icone_Youtube.svg
  src/View/Include/_footer.html.twig
  src/View/layout.html.twig
Labels: invalid

#4 Ajout page discographie et données dans les tables + modifications ta…
  public/assets/css/discography.css
  public/assets/css/style.css
  public/assets/images/1200x680_album.jpg
  public/assets/images/albums/asturzadenacht.webp
  public/assets/images/albums/nouvel_album.webp
  public/assets/images/albums/sommerzitt.webp
  public/assets/images/cigognelesassoifés.jpg
  public/assets/images/lesAssoifés_groupe.webp
  src/Controller/DiscographyController.php
  src/Model/DiscographyManager.php
  src/View/Discography/discography.html.twig
  src/routes.php
Labels: enhancement

#8 page groupe
  public/assets/css/_groupe.css
  public/assets/css/style.css
  public/assets/images/Groupe/Davele.jpg
  public/assets/images/Groupe/Guigues.jpg
  public/assets/images/Groupe/Nickes.jpg
  public/assets/images/Groupe/Philes.jpg
  public/assets/images/Groupe/Samele.jpg
  src/Controller/GroupeController.php
  src/View/Groupe/index.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: bug
